// GENERATED by scripts/gen-registry.ts — edit projections/hints in place; regen only when adding commands.
import type { CommandEntry } from "./lib/run-command.ts";
import getPing from "./commands/acculynx_get_ping.ts";
import getJobs from "./commands/acculynx_get_jobs.ts";
import getJob from "./commands/acculynx_get_job.ts";
import createJob from "./commands/acculynx_create_job.ts";
import getJobsByAssignedUser from "./commands/acculynx_get_jobs_by_assigned_user.ts";
import getJobContacts from "./commands/acculynx_get_job_contacts.ts";
import getJobContact from "./commands/acculynx_get_job_contact.ts";
import getJobCurrentMilestone from "./commands/acculynx_get_job_current_milestone.ts";
import getJobMilestoneById from "./commands/acculynx_get_job_milestone_by_id.ts";
import getJobMilestoneHistory from "./commands/acculynx_get_job_milestone_history.ts";
import getJobStatusById from "./commands/acculynx_get_job_status_by_id.ts";
import getLeadHistory from "./commands/acculynx_get_lead_history.ts";
import getJobProductionSchedule from "./commands/acculynx_get_job_production_schedule.ts";
import getJobExternalReferences from "./commands/acculynx_get_job_external_references.ts";
import postCreateJobExternalReference from "./commands/acculynx_post_create_job_external_reference.ts";
import getJobCustomFields from "./commands/acculynx_get_job_custom_fields.ts";
import getJobCustomFieldById from "./commands/acculynx_get_job_custom_field_by_id.ts";
import putJobCustomFields from "./commands/acculynx_put_job_custom_fields.ts";
import putJobCustomFieldById from "./commands/acculynx_put_job_custom_field_by_id.ts";
import getJobAccountingStatus from "./commands/acculynx_get_job_accounting_status.ts";
import getJobAdjuster from "./commands/acculynx_get_job_adjuster.ts";
import putAdjusterForJob from "./commands/acculynx_put_adjuster_for_job.ts";
import getJobInsurance from "./commands/acculynx_get_job_insurance.ts";
import putInsuranceInformationForJob from "./commands/acculynx_put_insurance_information_for_job.ts";
import putInsuranceCompanyForJob from "./commands/acculynx_put_insurance_company_for_job.ts";
import getJobRepresentatives from "./commands/acculynx_get_job_representatives.ts";
import getCompanyRepresentativeForJob from "./commands/acculynx_get_company_representative_for_job.ts";
import getSalesOwnerForJob from "./commands/acculynx_get_sales_owner_for_job.ts";
import getArOwnerForJob from "./commands/acculynx_get_ar_owner_for_job.ts";
import postCompanyRepresentativeForJob from "./commands/acculynx_post_company_representative_for_job.ts";
import postSalesOwnerForJob from "./commands/acculynx_post_sales_owner_for_job.ts";
import postArOwnerForJob from "./commands/acculynx_post_ar_owner_for_job.ts";
import deleteSalesOwnerFromJob from "./commands/acculynx_delete_sales_owner_from_job.ts";
import deleteArOwnerFromJob from "./commands/acculynx_delete_ar_owner_from_job.ts";
import putJobLocationAddress from "./commands/acculynx_put_job_location_address.ts";
import putPriorityForJob from "./commands/acculynx_put_priority_for_job.ts";
import updateJobCategory from "./commands/acculynx_update_job_category.ts";
import updateJobWorkType from "./commands/acculynx_update_job_work_type.ts";
import updateJobTradeTypes from "./commands/acculynx_update_job_trade_types.ts";
import updateJobLeadSource from "./commands/acculynx_update_job_lead_source.ts";
import createJobMessage from "./commands/acculynx_create_job_message.ts";
import postReplyJobMessage from "./commands/acculynx_post_reply_job_message.ts";
import getJobInitialAppointment from "./commands/acculynx_get_job_initial_appointment.ts";
import setInitialAppointment from "./commands/acculynx_set_initial_appointment.ts";
import deleteJobInitialAppointment from "./commands/acculynx_delete_job_initial_appointment.ts";
import postJobMeasurementsUpload from "./commands/acculynx_post_job_measurements_upload.ts";
import postJobMeasurementsUploadFiles from "./commands/acculynx_post_job_measurements_upload_files.ts";
import getContacts from "./commands/acculynx_get_contacts.ts";
import getContact from "./commands/acculynx_get_contact.ts";
import createContact from "./commands/acculynx_create_contact.ts";
import getContactTypes from "./commands/acculynx_get_contact_types.ts";
import addContactLog from "./commands/acculynx_add_contact_log.ts";
import getContactPhoneNumbers from "./commands/acculynx_get_contact_phone_numbers.ts";
import getContactPhoneNumberById from "./commands/acculynx_get_contact_phone_number_by_id.ts";
import getContactEmailAddresses from "./commands/acculynx_get_contact_email_addresses.ts";
import getContactEmailAddressById from "./commands/acculynx_get_contact_email_address_by_id.ts";
import getContactCustomFields from "./commands/acculynx_get_contact_custom_fields.ts";
import getContactCustomFieldById from "./commands/acculynx_get_contact_custom_field_by_id.ts";
import putContactCustomFields from "./commands/acculynx_put_contact_custom_fields.ts";
import putContactCustomFieldById from "./commands/acculynx_put_contact_custom_field_by_id.ts";
import getEstimates from "./commands/acculynx_get_estimates.ts";
import getEstimateById from "./commands/acculynx_get_estimate_by_id.ts";
import getJobEstimates from "./commands/acculynx_get_job_estimates.ts";
import getEstimateSections from "./commands/acculynx_get_estimate_sections.ts";
import getEstimateSectionById from "./commands/acculynx_get_estimate_section_by_id.ts";
import getEstimateSectionItems from "./commands/acculynx_get_estimate_section_items.ts";
import getEstimateSectionItem from "./commands/acculynx_get_estimate_section_item.ts";
import getJobFinancials from "./commands/acculynx_get_job_financials.ts";
import getFinancialsByFinancialId from "./commands/acculynx_get_financials_by_financial_id.ts";
import getWorksheetById from "./commands/acculynx_get_worksheet_by_id.ts";
import getWorksheetAmendmentsById from "./commands/acculynx_get_worksheet_amendments_by_id.ts";
import getWorksheetAmendmentById from "./commands/acculynx_get_worksheet_amendment_by_id.ts";
import postWorksheetSectionItem from "./commands/acculynx_post_worksheet_section_item.ts";
import getFinancialsSupplementsForCompany from "./commands/acculynx_get_financials_supplements_for_company.ts";
import getSupplementById from "./commands/acculynx_get_supplement_by_id.ts";
import getFinancialsSupplementItemCollection from "./commands/acculynx_get_financials_supplement_item_collection.ts";
import getFinancialsSupplementNotationCollection from "./commands/acculynx_get_financials_supplement_notation_collection.ts";
import getInvoice from "./commands/acculynx_get_invoice.ts";
import getJobInvoices from "./commands/acculynx_get_job_invoices.ts";
import getPayments from "./commands/acculynx_get_payments.ts";
import getJobPayments from "./commands/acculynx_get_job_payments.ts";
import createPaymentReceived from "./commands/acculynx_create_payment_received.ts";
import postCreatePaymentPaid from "./commands/acculynx_post_create_payment_paid.ts";
import postCreatePaymentAdditionalExpense from "./commands/acculynx_post_create_payment_additional_expense.ts";
import getCalendars from "./commands/acculynx_get_calendars.ts";
import getAppointments from "./commands/acculynx_get_appointments.ts";
import getAppointment from "./commands/acculynx_get_appointment.ts";
import getCompanyDocumentFolders from "./commands/acculynx_get_company_document_folders.ts";
import addJobDocument from "./commands/acculynx_add_job_document.ts";
import postUploadPhotoOrVideo from "./commands/acculynx_post_upload_photo_or_video.ts";
import getPhotoVideoTags from "./commands/acculynx_get_photo_video_tags.ts";
import getUsers from "./commands/acculynx_get_users.ts";
import getUser from "./commands/acculynx_get_user.ts";
import getCompanySettings from "./commands/acculynx_get_company_settings.ts";
import getMilestones from "./commands/acculynx_get_milestones.ts";
import getStatusesForMilestone from "./commands/acculynx_get_statuses_for_milestone.ts";
import getLeadSources from "./commands/acculynx_get_lead_sources.ts";
import getLeadSourceById from "./commands/acculynx_get_lead_source_by_id.ts";
import getLeadSourceChildById from "./commands/acculynx_get_lead_source_child_by_id.ts";
import getJobCategories from "./commands/acculynx_get_job_categories.ts";
import getWorkTypes from "./commands/acculynx_get_work_types.ts";
import getTradeTypes from "./commands/acculynx_get_trade_types.ts";
import getInsuranceCompanies from "./commands/acculynx_get_insurance_companies.ts";
import getCustomFields from "./commands/acculynx_get_custom_fields.ts";
import getActiveAccountTypes from "./commands/acculynx_get_active_account_types.ts";
import getAccountTypeById from "./commands/acculynx_get_account_type_by_id.ts";
import getCompanySettingsLocationSettingsCountries from "./commands/acculynx_get_company_settings_location_settings_countries.ts";
import getLocationSettingsCountryStates from "./commands/acculynx_get_location_settings_country_states.ts";
import getAccuLynxCountries from "./commands/acculynx_get_accu_lynx_countries.ts";
import getAccuLynxCountry from "./commands/acculynx_get_accu_lynx_country.ts";
import getAccuLynxStates from "./commands/acculynx_get_accu_lynx_states.ts";
import getAccuLynxState from "./commands/acculynx_get_accu_lynx_state.ts";
import getUnitsOfMeasure from "./commands/acculynx_get_units_of_measure.ts";
import getReportsByInstanceInstanceRunsByScheduleId from "./commands/acculynx_get_reports_by_instance_instance_runs_by_schedule_id.ts";
import getReportLatestInstance from "./commands/acculynx_get_report_latest_instance.ts";
import getReportByInstanceId from "./commands/acculynx_get_report_by_instance_id.ts";
import getReportsRecipientsByInstanceId from "./commands/acculynx_get_reports_recipients_by_instance_id.ts";
import getReportInstaceRecipientById from "./commands/acculynx_get_report_instace_recipient_by_id.ts";

export const GROUP_ORDER = [
  "jobs", "contacts", "estimates", "financials", "invoices", "payments",
  "appointments", "documents", "media", "users", "settings", "reports", "misc",
] as const;

export const REGISTRY: CommandEntry[] = [
  { group: "misc", verb: "ping", tool: "acculynx_get_ping", config: getPing },
  { group: "jobs", verb: "list", tool: "acculynx_get_jobs", config: getJobs,
    project: ["id", "jobNumber", "jobName", "currentMilestone", "createdDate", "modifiedDate"] },
  { group: "jobs", verb: "get", tool: "acculynx_get_job", config: getJob, positional: "jobId" },
  { group: "jobs", verb: "create", tool: "acculynx_create_job", config: createJob,
    hints: [
      "Inspect assignmentErrors above before reporting success.",
      "Assign reps later: acculynx jobs set-company-rep --json '{...}' (new leads: company reps only; sales/AR owners require Approved milestone).",
    ] },
  { group: "jobs", verb: "list-by-user", tool: "acculynx_get_jobs_by_assigned_user", config: getJobsByAssignedUser },
  { group: "jobs", verb: "contacts", tool: "acculynx_get_job_contacts", config: getJobContacts, positional: "jobId" },
  { group: "jobs", verb: "contact", tool: "acculynx_get_job_contact", config: getJobContact },
  { group: "jobs", verb: "current-milestone", tool: "acculynx_get_job_current_milestone", config: getJobCurrentMilestone, positional: "jobId" },
  { group: "jobs", verb: "milestone", tool: "acculynx_get_job_milestone_by_id", config: getJobMilestoneById },
  { group: "jobs", verb: "milestone-history", tool: "acculynx_get_job_milestone_history", config: getJobMilestoneHistory, positional: "jobId" },
  { group: "jobs", verb: "status", tool: "acculynx_get_job_status_by_id", config: getJobStatusById },
  { group: "jobs", verb: "lead-history", tool: "acculynx_get_lead_history", config: getLeadHistory, positional: "leadId" },
  { group: "jobs", verb: "production-schedule", tool: "acculynx_get_job_production_schedule", config: getJobProductionSchedule, positional: "jobId" },
  { group: "jobs", verb: "external-references", tool: "acculynx_get_job_external_references", config: getJobExternalReferences, positional: "jobId" },
  { group: "jobs", verb: "add-external-reference", tool: "acculynx_post_create_job_external_reference", config: postCreateJobExternalReference },
  { group: "jobs", verb: "custom-fields", tool: "acculynx_get_job_custom_fields", config: getJobCustomFields, positional: "jobId" },
  { group: "jobs", verb: "custom-field", tool: "acculynx_get_job_custom_field_by_id", config: getJobCustomFieldById },
  { group: "jobs", verb: "set-custom-fields", tool: "acculynx_put_job_custom_fields", config: putJobCustomFields, positional: "jobId" },
  { group: "jobs", verb: "set-custom-field", tool: "acculynx_put_job_custom_field_by_id", config: putJobCustomFieldById },
  { group: "jobs", verb: "accounting-status", tool: "acculynx_get_job_accounting_status", config: getJobAccountingStatus, positional: "jobId" },
  { group: "jobs", verb: "adjuster", tool: "acculynx_get_job_adjuster", config: getJobAdjuster, positional: "jobId" },
  { group: "jobs", verb: "set-adjuster", tool: "acculynx_put_adjuster_for_job", config: putAdjusterForJob, positional: "jobId" },
  { group: "jobs", verb: "insurance", tool: "acculynx_get_job_insurance", config: getJobInsurance, positional: "jobId" },
  { group: "jobs", verb: "set-insurance", tool: "acculynx_put_insurance_information_for_job", config: putInsuranceInformationForJob, positional: "jobId" },
  { group: "jobs", verb: "set-insurance-company", tool: "acculynx_put_insurance_company_for_job", config: putInsuranceCompanyForJob, positional: "jobId" },
  { group: "jobs", verb: "representatives", tool: "acculynx_get_job_representatives", config: getJobRepresentatives, positional: "jobId" },
  { group: "jobs", verb: "company-rep", tool: "acculynx_get_company_representative_for_job", config: getCompanyRepresentativeForJob, positional: "jobId" },
  { group: "jobs", verb: "sales-owner", tool: "acculynx_get_sales_owner_for_job", config: getSalesOwnerForJob, positional: "jobId" },
  { group: "jobs", verb: "ar-owner", tool: "acculynx_get_ar_owner_for_job", config: getArOwnerForJob, positional: "jobId" },
  { group: "jobs", verb: "set-company-rep", tool: "acculynx_post_company_representative_for_job", config: postCompanyRepresentativeForJob, positional: "jobId" },
  { group: "jobs", verb: "set-sales-owner", tool: "acculynx_post_sales_owner_for_job", config: postSalesOwnerForJob, positional: "jobId" },
  { group: "jobs", verb: "set-ar-owner", tool: "acculynx_post_ar_owner_for_job", config: postArOwnerForJob, positional: "jobId" },
  { group: "jobs", verb: "remove-sales-owner", tool: "acculynx_delete_sales_owner_from_job", config: deleteSalesOwnerFromJob, positional: "jobId" },
  { group: "jobs", verb: "remove-ar-owner", tool: "acculynx_delete_ar_owner_from_job", config: deleteArOwnerFromJob, positional: "jobId" },
  { group: "jobs", verb: "set-location", tool: "acculynx_put_job_location_address", config: putJobLocationAddress, positional: "jobId" },
  { group: "jobs", verb: "set-priority", tool: "acculynx_put_priority_for_job", config: putPriorityForJob, positional: "jobId" },
  { group: "jobs", verb: "set-category", tool: "acculynx_update_job_category", config: updateJobCategory, positional: "jobId" },
  { group: "jobs", verb: "set-work-type", tool: "acculynx_update_job_work_type", config: updateJobWorkType, positional: "jobId" },
  { group: "jobs", verb: "set-trade-types", tool: "acculynx_update_job_trade_types", config: updateJobTradeTypes, positional: "jobId" },
  { group: "jobs", verb: "set-lead-source", tool: "acculynx_update_job_lead_source", config: updateJobLeadSource },
  { group: "jobs", verb: "add-message", tool: "acculynx_create_job_message", config: createJobMessage, positional: "jobId" },
  { group: "jobs", verb: "reply-message", tool: "acculynx_post_reply_job_message", config: postReplyJobMessage },
  { group: "jobs", verb: "initial-appointment", tool: "acculynx_get_job_initial_appointment", config: getJobInitialAppointment, positional: "jobId" },
  { group: "jobs", verb: "set-initial-appointment", tool: "acculynx_set_initial_appointment", config: setInitialAppointment, positional: "jobId" },
  { group: "jobs", verb: "delete-initial-appointment", tool: "acculynx_delete_job_initial_appointment", config: deleteJobInitialAppointment, positional: "jobId" },
  { group: "jobs", verb: "upload-measurements", tool: "acculynx_post_job_measurements_upload", config: postJobMeasurementsUpload, positional: "jobId" },
  { group: "jobs", verb: "upload-measurement-files", tool: "acculynx_post_job_measurements_upload_files", config: postJobMeasurementsUploadFiles, positional: "jobId" },
  { group: "contacts", verb: "list", tool: "acculynx_get_contacts", config: getContacts,
    project: ["id", "firstName", "lastName", "companyName"] },
  { group: "contacts", verb: "get", tool: "acculynx_get_contact", config: getContact, positional: "contactId" },
  { group: "contacts", verb: "create", tool: "acculynx_create_contact", config: createContact,
    hints: ["Create a job for this contact: acculynx jobs create --json '{\"contact\":{\"id\":\"<id>\"}}'"] },
  { group: "contacts", verb: "types", tool: "acculynx_get_contact_types", config: getContactTypes },
  { group: "contacts", verb: "add-log", tool: "acculynx_add_contact_log", config: addContactLog, positional: "contactId" },
  { group: "contacts", verb: "phone-numbers", tool: "acculynx_get_contact_phone_numbers", config: getContactPhoneNumbers, positional: "contactId" },
  { group: "contacts", verb: "phone-number", tool: "acculynx_get_contact_phone_number_by_id", config: getContactPhoneNumberById },
  { group: "contacts", verb: "email-addresses", tool: "acculynx_get_contact_email_addresses", config: getContactEmailAddresses, positional: "contactId" },
  { group: "contacts", verb: "email-address", tool: "acculynx_get_contact_email_address_by_id", config: getContactEmailAddressById },
  { group: "contacts", verb: "custom-fields", tool: "acculynx_get_contact_custom_fields", config: getContactCustomFields, positional: "contactId" },
  { group: "contacts", verb: "custom-field", tool: "acculynx_get_contact_custom_field_by_id", config: getContactCustomFieldById },
  { group: "contacts", verb: "set-custom-fields", tool: "acculynx_put_contact_custom_fields", config: putContactCustomFields, positional: "contactId" },
  { group: "contacts", verb: "set-custom-field", tool: "acculynx_put_contact_custom_field_by_id", config: putContactCustomFieldById },
  { group: "estimates", verb: "list", tool: "acculynx_get_estimates", config: getEstimates,
    project: ["id", "isPrimary", "job.id"] },
  { group: "estimates", verb: "get", tool: "acculynx_get_estimate_by_id", config: getEstimateById, positional: "estimateId" },
  { group: "estimates", verb: "list-for-job", tool: "acculynx_get_job_estimates", config: getJobEstimates, positional: "jobId" },
  { group: "estimates", verb: "sections", tool: "acculynx_get_estimate_sections", config: getEstimateSections, positional: "estimateId" },
  { group: "estimates", verb: "section", tool: "acculynx_get_estimate_section_by_id", config: getEstimateSectionById },
  { group: "estimates", verb: "section-items", tool: "acculynx_get_estimate_section_items", config: getEstimateSectionItems },
  { group: "estimates", verb: "section-item", tool: "acculynx_get_estimate_section_item", config: getEstimateSectionItem },
  { group: "financials", verb: "for-job", tool: "acculynx_get_job_financials", config: getJobFinancials, positional: "jobId" },
  { group: "financials", verb: "get", tool: "acculynx_get_financials_by_financial_id", config: getFinancialsByFinancialId, positional: "financialsId" },
  { group: "financials", verb: "worksheet", tool: "acculynx_get_worksheet_by_id", config: getWorksheetById, positional: "financialsId" },
  { group: "financials", verb: "amendments", tool: "acculynx_get_worksheet_amendments_by_id", config: getWorksheetAmendmentsById, positional: "financialsId" },
  { group: "financials", verb: "amendment", tool: "acculynx_get_worksheet_amendment_by_id", config: getWorksheetAmendmentById },
  { group: "financials", verb: "add-worksheet-item", tool: "acculynx_post_worksheet_section_item", config: postWorksheetSectionItem, positional: "financialsId" },
  { group: "financials", verb: "supplements", tool: "acculynx_get_financials_supplements_for_company", config: getFinancialsSupplementsForCompany },
  { group: "financials", verb: "supplement", tool: "acculynx_get_supplement_by_id", config: getSupplementById, positional: "supplementId" },
  { group: "financials", verb: "supplement-items", tool: "acculynx_get_financials_supplement_item_collection", config: getFinancialsSupplementItemCollection, positional: "supplementId" },
  { group: "financials", verb: "supplement-notations", tool: "acculynx_get_financials_supplement_notation_collection", config: getFinancialsSupplementNotationCollection, positional: "supplementId" },
  { group: "invoices", verb: "get", tool: "acculynx_get_invoice", config: getInvoice, positional: "invoiceId" },
  { group: "invoices", verb: "list-for-job", tool: "acculynx_get_job_invoices", config: getJobInvoices, positional: "jobId" },
  { group: "payments", verb: "list", tool: "acculynx_get_payments", config: getPayments, positional: "jobId" },
  { group: "payments", verb: "for-job", tool: "acculynx_get_job_payments", config: getJobPayments, positional: "jobId" },
  { group: "payments", verb: "add-received", tool: "acculynx_create_payment_received", config: createPaymentReceived, positional: "jobId",
    hints: ["Verify: acculynx payments for-job <jobId>"] },
  { group: "payments", verb: "add-paid", tool: "acculynx_post_create_payment_paid", config: postCreatePaymentPaid, positional: "jobId",
    hints: ["Verify: acculynx payments for-job <jobId>"] },
  { group: "payments", verb: "add-expense", tool: "acculynx_post_create_payment_additional_expense", config: postCreatePaymentAdditionalExpense, positional: "jobId",
    hints: ["Verify: acculynx payments for-job <jobId>"] },
  { group: "appointments", verb: "calendars", tool: "acculynx_get_calendars", config: getCalendars },
  { group: "appointments", verb: "list", tool: "acculynx_get_appointments", config: getAppointments, positional: "calendarId" },
  { group: "appointments", verb: "get", tool: "acculynx_get_appointment", config: getAppointment },
  { group: "documents", verb: "folders", tool: "acculynx_get_company_document_folders", config: getCompanyDocumentFolders },
  { group: "documents", verb: "add", tool: "acculynx_add_job_document", config: addJobDocument,
    hints: ["Folder UUIDs come from: acculynx documents folders"] },
  { group: "media", verb: "upload", tool: "acculynx_post_upload_photo_or_video", config: postUploadPhotoOrVideo, positional: "jobId" },
  { group: "media", verb: "tags", tool: "acculynx_get_photo_video_tags", config: getPhotoVideoTags },
  { group: "users", verb: "list", tool: "acculynx_get_users", config: getUsers,
    project: ["id", "displayName", "email", "role", "status"] },
  { group: "users", verb: "get", tool: "acculynx_get_user", config: getUser, positional: "userId" },
  { group: "settings", verb: "company", tool: "acculynx_get_company_settings", config: getCompanySettings },
  { group: "settings", verb: "milestones", tool: "acculynx_get_milestones", config: getMilestones },
  { group: "settings", verb: "milestone-statuses", tool: "acculynx_get_statuses_for_milestone", config: getStatusesForMilestone },
  { group: "settings", verb: "lead-sources", tool: "acculynx_get_lead_sources", config: getLeadSources },
  { group: "settings", verb: "lead-source", tool: "acculynx_get_lead_source_by_id", config: getLeadSourceById, positional: "leadSourceId" },
  { group: "settings", verb: "lead-source-child", tool: "acculynx_get_lead_source_child_by_id", config: getLeadSourceChildById },
  { group: "settings", verb: "job-categories", tool: "acculynx_get_job_categories", config: getJobCategories },
  { group: "settings", verb: "work-types", tool: "acculynx_get_work_types", config: getWorkTypes },
  { group: "settings", verb: "trade-types", tool: "acculynx_get_trade_types", config: getTradeTypes },
  { group: "settings", verb: "insurance-companies", tool: "acculynx_get_insurance_companies", config: getInsuranceCompanies },
  { group: "settings", verb: "custom-fields", tool: "acculynx_get_custom_fields", config: getCustomFields },
  { group: "settings", verb: "account-types", tool: "acculynx_get_active_account_types", config: getActiveAccountTypes },
  { group: "settings", verb: "account-type", tool: "acculynx_get_account_type_by_id", config: getAccountTypeById, positional: "accountTypeId" },
  { group: "settings", verb: "countries", tool: "acculynx_get_company_settings_location_settings_countries", config: getCompanySettingsLocationSettingsCountries },
  { group: "settings", verb: "country-states", tool: "acculynx_get_location_settings_country_states", config: getLocationSettingsCountryStates, positional: "countryId" },
  { group: "settings", verb: "al-countries", tool: "acculynx_get_accu_lynx_countries", config: getAccuLynxCountries },
  { group: "settings", verb: "al-country", tool: "acculynx_get_accu_lynx_country", config: getAccuLynxCountry, positional: "countryId" },
  { group: "settings", verb: "al-states", tool: "acculynx_get_accu_lynx_states", config: getAccuLynxStates, positional: "countryId" },
  { group: "settings", verb: "al-state", tool: "acculynx_get_accu_lynx_state", config: getAccuLynxState },
  { group: "settings", verb: "units-of-measure", tool: "acculynx_get_units_of_measure", config: getUnitsOfMeasure },
  { group: "reports", verb: "runs", tool: "acculynx_get_reports_by_instance_instance_runs_by_schedule_id", config: getReportsByInstanceInstanceRunsByScheduleId, positional: "scheduledReportId" },
  { group: "reports", verb: "latest-run", tool: "acculynx_get_report_latest_instance", config: getReportLatestInstance, positional: "scheduledReportId" },
  { group: "reports", verb: "run", tool: "acculynx_get_report_by_instance_id", config: getReportByInstanceId },
  { group: "reports", verb: "run-recipients", tool: "acculynx_get_reports_recipients_by_instance_id", config: getReportsRecipientsByInstanceId },
  { group: "reports", verb: "run-recipient", tool: "acculynx_get_report_instace_recipient_by_id", config: getReportInstaceRecipientById },
];

export function findEntry(group: string | undefined, verb: string | undefined): CommandEntry | undefined {
  return REGISTRY.find((e) => e.group === group && e.verb === verb);
}
